version: '1.1'
services:
  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    environment:
      - APP_DSN=postgres://db/go_restful?sslmode=disable&user=postgres&password=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "go_restful"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/20191217202658_init.up.sql:/docker-entrypoint-initdb.d/init.sql


